// Code generated by protoc-gen-go. DO NOT EDIT.
// source: services/user.proto

package services

/*
go package: sample_services
*/

import (
	fmt "fmt"
	proto "github.com/golang/protobuf/proto"
	math "math"
	messages "messages"
)

import (
	context "golang.org/x/net/context"
	grpc "google.golang.org/grpc"
)

// Reference imports to suppress errors if they are not otherwise used.
var _ = proto.Marshal
var _ = fmt.Errorf
var _ = math.Inf

// This is a compile-time assertion to ensure that this generated file
// is compatible with the proto package it is being compiled against.
// A compilation error at this line likely means your copy of the
// proto package needs to be updated.
const _ = proto.ProtoPackageIsVersion2 // please upgrade the proto package

// Reference imports to suppress errors if they are not otherwise used.
var _ context.Context
var _ grpc.ClientConn

// This is a compile-time assertion to ensure that this generated file
// is compatible with the grpc package it is being compiled against.
const _ = grpc.SupportPackageIsVersion4

// UserServiceClient is the client API for UserService service.
//
// For semantics around ctx use and closing/ending streaming RPCs, please refer to https://godoc.org/google.golang.org/grpc#ClientConn.NewStream.
type UserServiceClient interface {
	Get(ctx context.Context, in *messages.User, opts ...grpc.CallOption) (*messages.User, error)
}

type userServiceClient struct {
	cc *grpc.ClientConn
}

func NewUserServiceClient(cc *grpc.ClientConn) UserServiceClient {
	return &userServiceClient{cc}
}

func (c *userServiceClient) Get(ctx context.Context, in *messages.User, opts ...grpc.CallOption) (*messages.User, error) {
	out := new(messages.User)
	err := c.cc.Invoke(ctx, "/sample.services.UserService/Get", in, out, opts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

// UserServiceServer is the server API for UserService service.
type UserServiceServer interface {
	Get(context.Context, *messages.User) (*messages.User, error)
}

func RegisterUserServiceServer(s *grpc.Server, srv UserServiceServer) {
	s.RegisterService(&_UserService_serviceDesc, srv)
}

func _UserService_Get_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(messages.User)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(UserServiceServer).Get(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: "/sample.services.UserService/Get",
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(UserServiceServer).Get(ctx, req.(*messages.User))
	}
	return interceptor(ctx, in, info, handler)
}

var _UserService_serviceDesc = grpc.ServiceDesc{
	ServiceName: "sample.services.UserService",
	HandlerType: (*UserServiceServer)(nil),
	Methods: []grpc.MethodDesc{
		{
			MethodName: "Get",
			Handler:    _UserService_Get_Handler,
		},
	},
	Streams:  []grpc.StreamDesc{},
	Metadata: "services/user.proto",
}

func init() { proto.RegisterFile("services/user.proto", fileDescriptor_43dec4b4b376a661) }

var fileDescriptor_43dec4b4b376a661 = []byte{
	// 121 bytes of a gzipped FileDescriptorProto
	0x1f, 0x8b, 0x08, 0x00, 0x00, 0x00, 0x00, 0x00, 0x02, 0xff, 0xe2, 0x12, 0x2e, 0x4e, 0x2d, 0x2a,
	0xcb, 0x4c, 0x4e, 0x2d, 0xd6, 0x2f, 0x2d, 0x4e, 0x2d, 0xd2, 0x2b, 0x28, 0xca, 0x2f, 0xc9, 0x17,
	0xe2, 0x2f, 0x4e, 0xcc, 0x2d, 0xc8, 0x49, 0xd5, 0x83, 0xc9, 0x49, 0x09, 0xe7, 0xa6, 0x16, 0x17,
	0x27, 0xa6, 0xa3, 0xa8, 0x32, 0x72, 0xe1, 0xe2, 0x0e, 0x2d, 0x4e, 0x2d, 0x0a, 0x86, 0x28, 0x12,
	0x32, 0xe5, 0x62, 0x76, 0x4f, 0x2d, 0x11, 0x12, 0xd5, 0x83, 0x6a, 0x86, 0x69, 0xd1, 0x03, 0x29,
	0x92, 0xc2, 0x2e, 0xac, 0xc4, 0xe0, 0x24, 0x13, 0xc5, 0x01, 0xb3, 0xe6, 0x14, 0x13, 0x7f, 0x30,
	0x58, 0x51, 0x0c, 0xd4, 0xcc, 0xe2, 0x24, 0x36, 0xb0, 0x55, 0xc6, 0x80, 0x00, 0x00, 0x00, 0xff,
	0xff, 0x15, 0x8f, 0xfa, 0xf4, 0xa7, 0x00, 0x00, 0x00,
}
