<?php
# Generated by the protocol buffer compiler.  DO NOT EDIT!
# source: services/user.proto

namespace GPBMetadata\Services;

class User
{
    public static $is_initialized = false;

    public static function initOnce() {
        $pool = \Google\Protobuf\Internal\DescriptorPool::getGeneratedPool();

        if (static::$is_initialized == true) {
          return;
        }
        \GPBMetadata\Messages\User::initOnce();
        $pool->internalAddGeneratedFile(hex2bin(
            "0ab4020a1373657276696365732f757365722e70726f746f122b6d797468726e722e70726f746f6275665f636f6d70696c65725f6578616d706c65732e7365727669636573327c0a0b5573657253657276696365126d0a0347657412312e6d797468726e722e70726f746f6275665f636f6d70696c65725f6578616d706c65732e6d657373616765732e557365721a312e6d797468726e722e70726f746f6275665f636f6d70696c65725f6578616d706c65732e6d657373616765732e557365722200426a5a3d6769746875622e636f6d2f6d797468726e722f70726f746f6275662d636f6d70696c65722f6578616d706c65732f676f6c616e672f7365727669636573ca02284d797468726e725c50726f746f627566436f6d70696c65724578616d706c655c5365727669636573620670726f746f33"
        ), true);

        static::$is_initialized = true;
    }
}

