<?php
# Generated by the protocol buffer compiler.  DO NOT EDIT!
# source: services/user.proto

namespace GPBMetadata\Services;

class User
{
    public static $is_initialized = false;

    public static function initOnce() {
        $pool = \Google\Protobuf\Internal\DescriptorPool::getGeneratedPool();

        if (static::$is_initialized == true) {
          return;
        }
        \GPBMetadata\Messages\User::initOnce();
        $pool->internalAddGeneratedFile(hex2bin(
            "0afa010a1373657276696365732f757365722e70726f746f121d6d797468" .
            "726e722e677270635f6578616d706c652e736572766963657332600a0b55" .
            "7365725365727669636512510a0347657412232e6d797468726e722e6772" .
            "70635f6578616d706c652e6d657373616765732e557365721a232e6d7974" .
            "68726e722e677270635f6578616d706c652e6d657373616765732e557365" .
            "722200425a5a396769746875622e636f6d2f6d797468726e722f67727063" .
            "2d636f6d70696c65722f6578616d706c65732f676f6c616e672f73657276" .
            "69636573ca021c4d797468726e725c477270634578616d706c655c536572" .
            "7669636573620670726f746f33"
        ));

        static::$is_initialized = true;
    }
}

