version: "3.8"

services:
  docs:
    build:
      context: "./docs"
      args: &buildargs
        HTTP_PROXY: "${HTTP_PROXY}"
        HTTPS_PROXY: "${HTTPS_PROXY}"
        LANG_VERSION: "${GO_VERSION:?required}"
        PROTOC_VERSION: "${PROTOC_VERSION:?required}"
    image: "mythrnr/protobuf-compiler:${PROTOC_VERSION}-docs"

  golang:
    build:
      context: "./golang"
      args: *buildargs
    image: "mythrnr/protobuf-compiler:${PROTOC_VERSION}-golang-${GO_VERSION}"

  php:
    build:
      context: "./php"
      args:
        <<: *buildargs
        LANG_VERSION: "${PHP_VERSION:?required}"
        PECL_GRPC_VERSION: "${PECL_GRPC_VERSION:?required}"
    image: "mythrnr/protobuf-compiler:${PROTOC_VERSION}-php-${PHP_VERSION}"

  python:
    build:
      context: "./python"
      args:
        <<: *buildargs
        LANG_VERSION: "${PYTHON_VERSION:?required}"
    image: "mythrnr/protobuf-compiler:${PROTOC_VERSION}-python-${PYTHON_VERSION}"
