version: '3.7'

services:
  docs:
    build:
      context: ./docs
      args: &buildargs
        HTTP_PROXY: "${HTTP_PROXY}"
        HTTPS_PROXY: "${HTTPS_PROXY}"
    image: "mythrnr/protobuf-compiler:docs"


  golang:
    build:
      context: ./golang
      args: *buildargs
    image: "mythrnr/protobuf-compiler:golang"


  php:
    build:
      context: ./php
      args: *buildargs
    image: "mythrnr/protobuf-compiler:php"


  python:
    build:
      context: ./python
      args: *buildargs
    image: "mythrnr/protobuf-compiler:python"
