version: '3.7'

services:
  golang:
    build:
      context: ./golang
      args: &buildargs
        HTTP_PROXY: "${HTTP_PROXY}"
        HTTPS_PROXY: "${HTTPS_PROXY}"
    image: "zdcconsumer/basis.protobuf-compiler:golang"


  docs:
    build:
      context: ./docs
      args: *buildargs
    image: "zdcconsumer/basis.protobuf-compiler:docs"


  php:
    build:
      context: ./php
      args: *buildargs
    image: "zdcconsumer/basis.protobuf-compiler:php"
