<?php
# Generated by the protocol buffer compiler.  DO NOT EDIT!
# source: messages/user.proto

namespace GPBMetadata\Messages;

class User
{
    public static $is_initialized = false;

    public static function initOnce() {
        $pool = \Google\Protobuf\Internal\DescriptorPool::getGeneratedPool();

        if (static::$is_initialized == true) {
          return;
        }
        \GPBMetadata\Google\Protobuf\Timestamp::initOnce();
        $pool->internalAddGeneratedFile(hex2bin(
            "0ab9020a136d657373616765732f757365722e70726f746f122b6d797468" .
            "726e722e70726f746f6275665f636f6d70696c65725f6578616d706c6573" .
            "2e6d657373616765732280010a0455736572120a0a026964180120012803" .
            "120c0a046e616d65180220012809122e0a0a637265617465645f61741803" .
            "2001280b321a2e676f6f676c652e70726f746f6275662e54696d65737461" .
            "6d70122e0a0a757064617465645f617418042001280b321a2e676f6f676c" .
            "652e70726f746f6275662e54696d657374616d70426a5a3d676974687562" .
            "2e636f6d2f6d797468726e722f70726f746f6275662d636f6d70696c6572" .
            "2f6578616d706c65732f676f6c616e672f6d65737361676573ca02284d79" .
            "7468726e725c50726f746f627566436f6d70696c65724578616d706c655c" .
            "4d65737361676573620670726f746f33"
        ), true);

        static::$is_initialized = true;
    }
}

