# -*- coding: utf-8 -*-
# Generated by the protocol buffer compiler.  DO NOT EDIT!
# source: services/user.proto

from google.protobuf import descriptor as _descriptor
from google.protobuf import message as _message
from google.protobuf import reflection as _reflection
from google.protobuf import symbol_database as _symbol_database
# @@protoc_insertion_point(imports)

_sym_db = _symbol_database.Default()


from messages import user_pb2 as messages_dot_user__pb2


DESCRIPTOR = _descriptor.FileDescriptor(
  name='services/user.proto',
  package='mythrnr.protobuf_compiler_examples.services',
  syntax='proto3',
  serialized_options=b'Z=github.com/mythrnr/protobuf-compiler/examples/golang/services\312\002(Mythrnr\\ProtobufCompilerExample\\Services',
  serialized_pb=b'\n\x13services/user.proto\x12+mythrnr.protobuf_compiler_examples.services\x1a\x13messages/user.proto2|\n\x0bUserService\x12m\n\x03Get\x12\x31.mythrnr.protobuf_compiler_examples.messages.User\x1a\x31.mythrnr.protobuf_compiler_examples.messages.User\"\x00\x42jZ=github.com/mythrnr/protobuf-compiler/examples/golang/services\xca\x02(Mythrnr\\ProtobufCompilerExample\\Servicesb\x06proto3'
  ,
  dependencies=[messages_dot_user__pb2.DESCRIPTOR,])



_sym_db.RegisterFileDescriptor(DESCRIPTOR)


DESCRIPTOR._options = None

_USERSERVICE = _descriptor.ServiceDescriptor(
  name='UserService',
  full_name='mythrnr.protobuf_compiler_examples.services.UserService',
  file=DESCRIPTOR,
  index=0,
  serialized_options=None,
  serialized_start=89,
  serialized_end=213,
  methods=[
  _descriptor.MethodDescriptor(
    name='Get',
    full_name='mythrnr.protobuf_compiler_examples.services.UserService.Get',
    index=0,
    containing_service=None,
    input_type=messages_dot_user__pb2._USER,
    output_type=messages_dot_user__pb2._USER,
    serialized_options=None,
  ),
])
_sym_db.RegisterServiceDescriptor(_USERSERVICE)

DESCRIPTOR.services_by_name['UserService'] = _USERSERVICE

# @@protoc_insertion_point(module_scope)
