# Generated by the protocol buffer compiler.  DO NOT EDIT!
# source: services/user.proto

import sys
_b=sys.version_info[0]<3 and (lambda x:x) or (lambda x:x.encode('latin1'))
from google.protobuf import descriptor as _descriptor
from google.protobuf import message as _message
from google.protobuf import reflection as _reflection
from google.protobuf import symbol_database as _symbol_database
# @@protoc_insertion_point(imports)

_sym_db = _symbol_database.Default()


from messages import user_pb2 as messages_dot_user__pb2


DESCRIPTOR = _descriptor.FileDescriptor(
  name='services/user.proto',
  package='mythrnr.grpc_example.services',
  syntax='proto3',
  serialized_options=_b('Z9github.com/mythrnr/grpc-compiler/examples/golang/services\312\002\034Mythrnr\\GrpcExample\\Services'),
  serialized_pb=_b('\n\x13services/user.proto\x12\x1dmythrnr.grpc_example.services\x1a\x13messages/user.proto2`\n\x0bUserService\x12Q\n\x03Get\x12#.mythrnr.grpc_example.messages.User\x1a#.mythrnr.grpc_example.messages.User\"\x00\x42ZZ9github.com/mythrnr/grpc-compiler/examples/golang/services\xca\x02\x1cMythrnr\\GrpcExample\\Servicesb\x06proto3')
  ,
  dependencies=[messages_dot_user__pb2.DESCRIPTOR,])



_sym_db.RegisterFileDescriptor(DESCRIPTOR)


DESCRIPTOR._options = None

_USERSERVICE = _descriptor.ServiceDescriptor(
  name='UserService',
  full_name='mythrnr.grpc_example.services.UserService',
  file=DESCRIPTOR,
  index=0,
  serialized_options=None,
  serialized_start=75,
  serialized_end=171,
  methods=[
  _descriptor.MethodDescriptor(
    name='Get',
    full_name='mythrnr.grpc_example.services.UserService.Get',
    index=0,
    containing_service=None,
    input_type=messages_dot_user__pb2._USER,
    output_type=messages_dot_user__pb2._USER,
    serialized_options=None,
  ),
])
_sym_db.RegisterServiceDescriptor(_USERSERVICE)

DESCRIPTOR.services_by_name['UserService'] = _USERSERVICE

# @@protoc_insertion_point(module_scope)
