version: '3.7'

# container to compile .proto files
services:
  docs:
    image: "mythrnr/protobuf-compiler:3.9.0-docs"
    volumes:
      - ./proto/:/proto/:ro
      - ./docs/:/output/:rw


  golang:
    image: "mythrnr/protobuf-compiler:3.9.0-golang"
    environment:
      PACKAGE_ROOT: "github.com/mythrnr/protobuf-compiler"
    volumes:
      - ./proto/:/proto/:ro
      - ../:/output/:rw


  php:
    image: "mythrnr/protobuf-compiler:3.9.0-php"
    volumes:
      - ./proto/:/proto/:ro
      - ./php/:/output/:rw


  python:
    image: "mythrnr/protobuf-compiler:3.9.0-python"
    volumes:
      - ./proto/:/proto/:ro
      - ./python/:/output/:rw
