version: "3.8"

# container to compile .proto files
services:
  docs:
    image: "mythrnr/protobuf-compiler:3.15.7-docs"
    volumes:
      - type: "bind"
        source: "./proto"
        target: "/proto"
        read_only: true
      - type: "bind"
        source: "./docs"
        target: "/output"
        read_only: false

  golang:
    image: "mythrnr/protobuf-compiler:3.15.7-golang-1.16"
    environment:
      PACKAGE_ROOT: "github.com/mythrnr/protobuf-compiler"
    volumes:
      - type: "bind"
        source: "./proto"
        target: "/proto"
        read_only: true
      - type: "bind"
        source: ".."
        target: "/output"
        read_only: false

  php:
    image: "mythrnr/protobuf-compiler:3.15.7-php-7.4"
    volumes:
      - type: "bind"
        source: "./proto"
        target: "/proto"
        read_only: true
      - type: "bind"
        source: "./php"
        target: "/output"
        read_only: false

  python:
    image: "mythrnr/protobuf-compiler:3.15.7-python-3.9"
    volumes:
      - type: "bind"
        source: "./proto"
        target: "/proto"
        read_only: true
      - type: "bind"
        source: "./python"
        target: "/output"
        read_only: false
