version: "3.8"

# container to compile .proto files
services:
  docs:
    image: "mythrnr/protobuf-compiler:3.14.0-docs"
    volumes:
      - "./proto/:/proto/:ro"
      - "./docs/:/output/:rw"

  golang:
    image: "mythrnr/protobuf-compiler:3.14.0-golang-1.15"
    environment:
      PACKAGE_ROOT: "github.com/mythrnr/protobuf-compiler"
    volumes:
      - "./proto/:/proto/:ro"
      - "../:/output/:rw"

  php:
    image: "mythrnr/protobuf-compiler:3.14.0-php-7.4"
    volumes:
      - "./proto/:/proto/:ro"
      - "./php/:/output/:rw"

  python:
    image: "mythrnr/protobuf-compiler:3.14.0-python-3.9"
    volumes:
      - "./proto/:/proto/:ro"
      - "./python/:/output/:rw"
