# via https://docs.github.com/en/actions/creating-actions/creating-a-composite-run-steps-action#creating-an-action-metadata-file
name: "Build and Push Images"
description: "Build docker image and push to dockerhub."
inputs:
  lang:
    description: "Target to build (docs|go|php|python)"
    required: true
  go:
    description: "Go version for building golang"
    required: true
    default: "1.16"
  pecl_grpc:
    description: "PECL::gRPC version for building php"
    required: true
    default: "1.37.0"
  php:
    description: "PHP version for building php"
    required: true
    default: "7.4"
  protoc:
    description: "Protocol Buffer version for building all images"
    required: true
    default: "3.15.8"
  python:
    description: "Python version for building python"
    required: true
    default: "3.9"
runs:
  using: "composite"
  steps:
    - shell: "bash"
      run: |
        make ${{ inputs.lang }} \
          go=${{ inputs.go }} \
          pecl_grpc=${{ inputs.pecl_grpc }} \
          php=${{ inputs.php }} \
          protoc=${{ inputs.protoc }} \
          python=${{ inputs.python }}

        make check \
          service=${{ inputs.lang }} \
          go=${{ inputs.go }} \
          pecl_grpc=${{ inputs.pecl_grpc }} \
          php=${{ inputs.php }} \
          protoc=${{ inputs.protoc }} \
          python=${{ inputs.python }}

        make push \
          service=${{ inputs.lang }} \
          go=${{ inputs.go }} \
          pecl_grpc=${{ inputs.pecl_grpc }} \
          php=${{ inputs.php }} \
          protoc=${{ inputs.protoc }} \
          python=${{ inputs.python }}
