// Code generated by protoc-gen-go. DO NOT EDIT.
// source: services/user.proto

package services

import (
	context "context"
	fmt "fmt"
	proto "github.com/golang/protobuf/proto"
	messages "github.com/mythrnr/protobuf-compiler/examples/golang/messages"
	grpc "google.golang.org/grpc"
	codes "google.golang.org/grpc/codes"
	status "google.golang.org/grpc/status"
	math "math"
)

// Reference imports to suppress errors if they are not otherwise used.
var _ = proto.Marshal
var _ = fmt.Errorf
var _ = math.Inf

// This is a compile-time assertion to ensure that this generated file
// is compatible with the proto package it is being compiled against.
// A compilation error at this line likely means your copy of the
// proto package needs to be updated.
const _ = proto.ProtoPackageIsVersion3 // please upgrade the proto package

func init() { proto.RegisterFile("services/user.proto", fileDescriptor_43dec4b4b376a661) }

var fileDescriptor_43dec4b4b376a661 = []byte{
	// 185 bytes of a gzipped FileDescriptorProto
	0x1f, 0x8b, 0x08, 0x00, 0x00, 0x00, 0x00, 0x00, 0x02, 0xff, 0xe2, 0x12, 0x2e, 0x4e, 0x2d, 0x2a,
	0xcb, 0x4c, 0x4e, 0x2d, 0xd6, 0x2f, 0x2d, 0x4e, 0x2d, 0xd2, 0x2b, 0x28, 0xca, 0x2f, 0xc9, 0x17,
	0xd2, 0xce, 0xad, 0x2c, 0xc9, 0x28, 0xca, 0x83, 0x72, 0x93, 0x4a, 0xd3, 0xe2, 0x93, 0xf3, 0x73,
	0x0b, 0x32, 0x73, 0x52, 0x8b, 0xe2, 0x53, 0x2b, 0x12, 0x73, 0x0b, 0x72, 0x52, 0x8b, 0xf5, 0x60,
	0xfa, 0xa4, 0x84, 0x73, 0x53, 0x8b, 0x8b, 0x13, 0xd3, 0x51, 0x4c, 0x30, 0xaa, 0xe1, 0xe2, 0x0e,
	0x2d, 0x4e, 0x2d, 0x0a, 0x86, 0x28, 0x12, 0xca, 0xe5, 0x62, 0x76, 0x4f, 0x2d, 0x11, 0x32, 0xd4,
	0x23, 0xc2, 0x60, 0x98, 0x71, 0x7a, 0x20, 0x03, 0xa4, 0x48, 0xd7, 0xa2, 0xc4, 0xe0, 0x94, 0x15,
	0x65, 0x9b, 0x9e, 0x59, 0x92, 0x51, 0x9a, 0xa4, 0x97, 0x9c, 0x9f, 0xab, 0x0f, 0x35, 0x40, 0x1f,
	0x66, 0x80, 0x2e, 0xcc, 0x00, 0x7d, 0x98, 0x01, 0xfa, 0xe9, 0xf9, 0x39, 0x89, 0x79, 0xe9, 0xfa,
	0x30, 0x3f, 0x9d, 0x62, 0xd2, 0xf0, 0x85, 0x68, 0x8a, 0x09, 0x80, 0x6a, 0x72, 0x86, 0xea, 0x71,
	0x85, 0x68, 0x89, 0x81, 0xfa, 0xac, 0x38, 0x89, 0x0d, 0x6c, 0xac, 0x31, 0x20, 0x00, 0x00, 0xff,
	0xff, 0x1e, 0x84, 0x4f, 0xbf, 0x49, 0x01, 0x00, 0x00,
}

// Reference imports to suppress errors if they are not otherwise used.
var _ context.Context
var _ grpc.ClientConn

// This is a compile-time assertion to ensure that this generated file
// is compatible with the grpc package it is being compiled against.
const _ = grpc.SupportPackageIsVersion4

// UserServiceClient is the client API for UserService service.
//
// For semantics around ctx use and closing/ending streaming RPCs, please refer to https://godoc.org/google.golang.org/grpc#ClientConn.NewStream.
type UserServiceClient interface {
	// get user request
	Get(ctx context.Context, in *messages.User, opts ...grpc.CallOption) (*messages.User, error)
}

type userServiceClient struct {
	cc *grpc.ClientConn
}

func NewUserServiceClient(cc *grpc.ClientConn) UserServiceClient {
	return &userServiceClient{cc}
}

func (c *userServiceClient) Get(ctx context.Context, in *messages.User, opts ...grpc.CallOption) (*messages.User, error) {
	out := new(messages.User)
	err := c.cc.Invoke(ctx, "/mythrnr.protobuf_compiler_examples.services.UserService/Get", in, out, opts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

// UserServiceServer is the server API for UserService service.
type UserServiceServer interface {
	// get user request
	Get(context.Context, *messages.User) (*messages.User, error)
}

// UnimplementedUserServiceServer can be embedded to have forward compatible implementations.
type UnimplementedUserServiceServer struct {
}

func (*UnimplementedUserServiceServer) Get(ctx context.Context, req *messages.User) (*messages.User, error) {
	return nil, status.Errorf(codes.Unimplemented, "method Get not implemented")
}

func RegisterUserServiceServer(s *grpc.Server, srv UserServiceServer) {
	s.RegisterService(&_UserService_serviceDesc, srv)
}

func _UserService_Get_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(messages.User)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(UserServiceServer).Get(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: "/mythrnr.protobuf_compiler_examples.services.UserService/Get",
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(UserServiceServer).Get(ctx, req.(*messages.User))
	}
	return interceptor(ctx, in, info, handler)
}

var _UserService_serviceDesc = grpc.ServiceDesc{
	ServiceName: "mythrnr.protobuf_compiler_examples.services.UserService",
	HandlerType: (*UserServiceServer)(nil),
	Methods: []grpc.MethodDesc{
		{
			MethodName: "Get",
			Handler:    _UserService_Get_Handler,
		},
	},
	Streams:  []grpc.StreamDesc{},
	Metadata: "services/user.proto",
}
