<?php
# Generated by the protocol buffer compiler.  DO NOT EDIT!
# source: messages/user.proto

namespace GPBMetadata\Messages;

class User
{
    public static $is_initialized = false;

    public static function initOnce() {
        $pool = \Google\Protobuf\Internal\DescriptorPool::getGeneratedPool();

        if (static::$is_initialized == true) {
          return;
        }
        \GPBMetadata\Google\Protobuf\Timestamp::initOnce();
        $pool->internalAddGeneratedFile(hex2bin(
            "0acf010a136d657373616765732f757365722e70726f746f120f73616d70" .
            "6c652e6d657373616765732280010a0455736572120a0a02696418012001" .
            "2803120c0a046e616d65180220012809122e0a0a637265617465645f6174" .
            "18032001280b321a2e676f6f676c652e70726f746f6275662e54696d6573" .
            "74616d70122e0a0a757064617465645f617418042001280b321a2e676f6f" .
            "676c652e70726f746f6275662e54696d657374616d70421c5a086d657373" .
            "61676573ca020f53616d706c655c4d65737361676573620670726f746f33"
        ));

        static::$is_initialized = true;
    }
}

