<?php
# Generated by the protocol buffer compiler.  DO NOT EDIT!
# source: services/user.proto

namespace GPBMetadata\Services;

class User
{
    public static $is_initialized = false;

    public static function initOnce() {
        $pool = \Google\Protobuf\Internal\DescriptorPool::getGeneratedPool();

        if (static::$is_initialized == true) {
          return;
        }
        \GPBMetadata\Messages\User::initOnce();
        $pool->internalAddGeneratedFile(hex2bin(
            "0a92010a1373657276696365732f757365722e70726f746f120f73616d70" .
            "6c652e736572766963657332440a0b557365725365727669636512350a03" .
            "47657412152e73616d706c652e6d657373616765732e557365721a152e73" .
            "616d706c652e6d657373616765732e557365722200421c5a087365727669" .
            "636573ca020f53616d706c655c5365727669636573620670726f746f33"
        ));

        static::$is_initialized = true;
    }
}

