name: "Build Image for Documenter"

on:
  push:
    branches:
      - "master"
    paths:
      - "**docs**"
  schedule:
    - cron: "0 12 * * 2"
  workflow_dispatch:

jobs:
  build:
    name: "Build"
    runs-on: "ubuntu-latest"
    strategy:
      matrix:
        protobuf_version:
          - "3.13.0"
          - "3.14.0"
          - "3.15.8"
    steps:
      - uses: "actions/checkout@v2"

      - uses: "./.github/actions/install-checker"

      - name: "Login Dockerhub"
        uses: "docker/login-action@v1"
        with:
          username: "${{ secrets.DOCKERHUB_USERNAME }}"
          password: "${{ secrets.DOCKERHUB_TOKEN }}"

      - uses: "./.github/actions/release-image"
        with:
          lang: "docs"
          protoc: "${{ matrix.protobuf_version }}"
