name: "Build Image for Documenter"

on:
  push:
    branches:
      - "master"
    paths:
      - "**docs**"
  schedule:
    - cron: "0 12 * * 2"
  workflow_dispatch:

jobs:
  build:
    name: "Build"
    runs-on: "ubuntu-latest"
    strategy:
      matrix:
        protobuf_version:
          - "3.13.0"
          - "3.14.0"
          - "3.15.7"
    steps:
      - uses: "actions/checkout@v2"

      - name: "Install trivy"
        run: |
          sudo apt install apt-transport-https gnupg
          wget -qO - https://aquasecurity.github.io/trivy-repo/deb/public.key \
            | sudo apt-key add -
          echo deb https://aquasecurity.github.io/trivy-repo/deb $(lsb_release -cs) main \
            | sudo tee -a /etc/apt/sources.list.d/trivy.list
          sudo apt update
          sudo apt install --no-install-recommends trivy

      - name: "Install dockle"
        run: |
          VERSION=$(
            curl --silent "https://api.github.com/repos/goodwithtech/dockle/releases/latest" \
              | grep '"tag_name":' \
              | sed -E 's/.*"v([^"]+)".*/\1/' \
          ) \
          && curl -L -o dockle.deb https://github.com/goodwithtech/dockle/releases/download/v${VERSION}/dockle_${VERSION}_Linux-64bit.deb

          sudo dpkg -i dockle.deb && rm dockle.deb

      - name: "Login Dockerhub"
        uses: "docker/login-action@v1"
        with:
          username: "${{ secrets.DOCKERHUB_USERNAME }}"
          password: "${{ secrets.DOCKERHUB_TOKEN }}"

      - name: "Build Image"
        run: |
          make docs \
            protoc=${{ matrix.protobuf_version }}

          make check \
            service=docs \
            protoc=${{ matrix.protobuf_version }}

      - name: "Push Image"
        run: |
          make push \
            service=docs \
            protoc=${{ matrix.protobuf_version }}
