name: "Build Image Golang"

on:
  push:
    branches:
      - "master"
    paths:
      - "**golang**"
  workflow_dispatch:

jobs:
  build:
    name: "Build"
    runs-on: "ubuntu-latest"
    strategy:
      matrix:
        go_version:
          - "1.14"
          - "1.15"
        protobuf_version:
          - "3.13.0"
          - "3.14.0"
    steps:
      - uses: "actions/checkout@v2"

      - name: "Install trivy"
        run: |
          sudo apt install apt-transport-https gnupg
          wget -qO - https://aquasecurity.github.io/trivy-repo/deb/public.key | sudo apt-key add -
          echo deb https://aquasecurity.github.io/trivy-repo/deb $(lsb_release -cs) main | sudo tee -a /etc/apt/sources.list.d/trivy.list
          sudo apt update
          sudo apt install --no-install-recommends trivy

      - name: "Login Dockerhub"
        uses: "docker/login-action@v1"
        with:
          username: ${{ secrets.DOCKERHUB_USERNAME }}
          password: ${{ secrets.DOCKERHUB_TOKEN }}

      - name: "Build Image"
        run: |
          make golang \
            go=${{ matrix.go_version }} \
            protoc=${{ matrix.protobuf_version }}

          make trivy service=golang \
            go=${{ matrix.go_version }} \
            protoc=${{ matrix.protobuf_version }}

      - name: "Push Image"
        run: |
          make push service=golang \
            go=${{ matrix.go_version }} \
            protoc=${{ matrix.protobuf_version }}
