name: "Build Image Golang"

on:
  push:
    branches:
      - "master"

jobs:
  build:
    name: "Build"
    runs-on: "ubuntu-latest"
    strategy:
      matrix:
        protobuf_version:
          - "3.9.0"
          - "3.10.1"
          - "3.11.2"
    env:
      PECL_GRPC_VERSION: "1.26.0"
      PROTOC_VERSION: "${{ matrix.protobuf_version }}"
    steps:
      - name: "Login Dockerhub"
        run: |
          docker login \
            --username ${{ secrets.DOCKERHUB_USERNAME }} \
            --password ${{ secrets.DOCKERHUB_PASSWORD }}
      - uses: "actions/checkout@master"
      - name: "Build Image"
        run: "docker-compose build golang"
      - name: "Push Image"
        run: "docker-compose push golang"

  build-latest:
    name: "Build Latest"
    needs:
      - "build"
    runs-on: "ubuntu-latest"
    env:
      PROTOC_VERSION: "3.11.2"
    steps:
      - name: "Login Dockerhub"
        run: |
          docker login \
            --username ${{ secrets.DOCKERHUB_USERNAME }} \
            --password ${{ secrets.DOCKERHUB_PASSWORD }}
      - name: "Pull Image"
        run: "docker pull mythrnr/protobuf-compiler:${PROTOC_VERSION}-golang"
      - name: "Tag Latest Image"
        run: |
          docker tag \
            mythrnr/protobuf-compiler:${PROTOC_VERSION}-golang \
            mythrnr/protobuf-compiler:latest-golang
      - name: "Push Image"
        run: "docker push mythrnr/protobuf-compiler:latest-golang"
