name: "Build Image for PHP"

on:
  # FIXME: https://github.com/grpc/grpc の Makefile から grpc_php_plugin が消えてビルドできないので一旦停止.
  # push:
  #   branches:
  #     - "master"
  #   paths:
  #     - "**php**"
  # schedule:
  #   - cron: "0 12 * * 2"
  workflow_dispatch:

jobs:
  build:
    name: "Build"
    runs-on: "ubuntu-latest"
    strategy:
      matrix:
        php:
          - "7.3"
          - "7.4"
        protoc:
          - "3.13.0"
          - "3.14.0"
          - "3.15.8"
    env:
      PECL_GRPC_VERSION: "1.37.0"
    steps:
      - uses: "actions/checkout@v2"

      - uses: "./.github/actions/install-checker"

      - name: "Login Dockerhub"
        uses: "docker/login-action@v1"
        with:
          username: "${{ secrets.DOCKERHUB_USERNAME }}"
          password: "${{ secrets.DOCKERHUB_TOKEN }}"

      - uses: "./.github/actions/release-image"
        with:
          lang: "php"
          pecl_grpc: "${{ env.PECL_GRPC_VERSION }}"
          php: "${{ matrix.php }}"
          protoc: "${{ matrix.protoc }}"
