name: "Build Image for PHP"

on:
  push:
    branches:
      - "master"
    paths:
      - "**php**"
  workflow_dispatch:

jobs:
  build:
    name: "Build"
    runs-on: "ubuntu-latest"
    strategy:
      matrix:
        protobuf_version:
          - "3.12.4"
          - "3.13.0"
        pecl_grpc_version:
          - "1.30.0"
          - "1.31.1"
    env:
      PECL_GRPC_VERSION: "${{ matrix.pecl_grpc_version }}"
      PROTOC_VERSION: "${{ matrix.protobuf_version }}"
    steps:
      - uses: "actions/checkout@v2"

      - name: "Install trivy"
        run: |
          sudo apt install apt-transport-https gnupg
          wget -qO - https://aquasecurity.github.io/trivy-repo/deb/public.key | sudo apt-key add -
          echo deb https://aquasecurity.github.io/trivy-repo/deb $(lsb_release -cs) main | sudo tee -a /etc/apt/sources.list.d/trivy.list
          sudo apt update
          sudo apt install --no-install-recommends trivy

      - name: "Login Dockerhub"
        uses: "docker/login-action@v1"
        with:
          username: ${{ secrets.DOCKERHUB_USERNAME }}
          password: ${{ secrets.DOCKERHUB_TOKEN }}

      - name: "Build Image"
        run: make build service=php

      - name: "Push Image"
        run: make push service=php

  build-latest:
    name: "Build Latest"
    needs:
      - "build"
    runs-on: "ubuntu-latest"
    env:
      PECL_GRPC_VERSION: "1.31.1"
      PROTOC_VERSION: "3.13.0"
    steps:
      - name: "Login Dockerhub"
        uses: "docker/login-action@v1"
        with:
          username: ${{ secrets.DOCKERHUB_USERNAME }}
          password: ${{ secrets.DOCKERHUB_TOKEN }}

      - name: "Pull Image"
        run: "docker pull mythrnr/protobuf-compiler:${PROTOC_VERSION}-php"

      - name: "Tag Latest Image"
        run: |
          docker tag \
            mythrnr/protobuf-compiler:${PROTOC_VERSION}-php \
            mythrnr/protobuf-compiler:latest-php

      - name: "Push Image"
        run: "docker push mythrnr/protobuf-compiler:latest-php"
