name: "Build Image for Python"

on:
  push:
    branches:
      - "master"
    paths:
      - "**python**"

jobs:
  build:
    name: "Build"
    runs-on: "ubuntu-latest"
    strategy:
      matrix:
        protobuf_version:
          - "3.9.2"
          - "3.10.1"
          - "3.11.2"
          - "3.12.2"
    env:
      PECL_GRPC_VERSION: "1.29.1"
      PROTOC_VERSION: "${{ matrix.protobuf_version }}"
    steps:
      - name: "Install trivy"
        run: |
          sudo apt install apt-transport-https gnupg
          wget -qO - https://aquasecurity.github.io/trivy-repo/deb/public.key | sudo apt-key add -
          echo deb https://aquasecurity.github.io/trivy-repo/deb $(lsb_release -cs) main | sudo tee -a /etc/apt/sources.list.d/trivy.list
          sudo apt update
          sudo apt install --no-install-recommends trivy

      - name: "Login Dockerhub"
        run: |
          docker login \
            --username ${{ secrets.DOCKERHUB_USERNAME }} \
            --password ${{ secrets.DOCKERHUB_PASSWORD }}

      - uses: "actions/checkout@v2"

      - name: "Build Image"
        run: make build service=python

      - name: "Push Image"
        run: make push service=python

  build-latest:
    name: "Build Latest"
    needs:
      - "build"
    runs-on: "ubuntu-latest"
    env:
      PECL_GRPC_VERSION: "1.29.1"
      PROTOC_VERSION: "3.12.2"
    steps:
      - name: "Login Dockerhub"
        run: |
          docker login \
            --username ${{ secrets.DOCKERHUB_USERNAME }} \
            --password ${{ secrets.DOCKERHUB_PASSWORD }}

      - name: "Pull Image"
        run: "docker pull mythrnr/protobuf-compiler:${PROTOC_VERSION}-python"

      - name: "Tag Latest Image"
        run: |
          docker tag \
            mythrnr/protobuf-compiler:${PROTOC_VERSION}-python \
            mythrnr/protobuf-compiler:latest-python

      - name: "Push Image"
        run: "docker push mythrnr/protobuf-compiler:latest-python"
